"""Data models for RoboCasa-generated scenes."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class SpawnPose:
    """Initial root-body pose for the project robot in MuJoCo world coordinates.

    Attributes:
        pos: Position in MuJoCo world coordinates, expressed as ``(x, y, z)``.
        quat: Orientation as a MuJoCo ``wxyz`` quaternion.
    """

    pos: tuple[float, float, float]
    quat: tuple[float, float, float, float]


@dataclass(frozen=True)
class ObjectPlacement:
    """Placement information for one object generated by a RoboCasa task.

    Attributes:
        name: RoboCasa object instance name.
        category: RoboCasa object category, if available.
        pos: Object position in MuJoCo world coordinates.
        quat: Object orientation as a MuJoCo ``wxyz`` quaternion.
    """

    name: str
    category: str | None
    pos: tuple[float, float, float]
    quat: tuple[float, float, float, float]


@dataclass(frozen=True)
class SceneMetadata:
    """Metadata describing a RoboCasa-generated scene.

    Attributes:
        task_name: RoboCasa task name passed to ``robosuite.make``.
        layout_id: RoboCasa kitchen layout id.
        style_id: RoboCasa kitchen style id.
        spawn_pose: Recommended robot spawn pose, if available.
        object_placements: Object placements generated by RoboCasa.
        raw_object_cfgs: Raw RoboCasa object configuration dictionaries.
    """

    task_name: str
    layout_id: int
    style_id: int
    spawn_pose: SpawnPose | None = None
    object_placements: tuple[ObjectPlacement, ...] = field(default_factory=tuple)
    raw_object_cfgs: tuple[dict[str, Any], ...] = field(default_factory=tuple)


@dataclass(frozen=True)
class GeneratedScene:
    """Final adapted scene returned by :class:`SceneGenerator`.

    Attributes:
        model: A ``mujoco.MjModel`` instance.
        xml: Final adapted MJCF XML string.
        metadata: Scene metadata and RoboCasa placement information.
    """

    model: Any
    xml: str
    metadata: SceneMetadata
